# frozen_string_literal: true

module NfgUi
  module Bootstrap
    # The manifest of all Bootstrap Components
    module Components
      require_relative 'components/base'
      require_relative 'components/alert'
      require_relative 'components/badge'
      require_relative 'components/breadcrumb'
      require_relative 'components/breadcrumb_item'
      require_relative 'components/button'
      require_relative 'components/button_group'
      require_relative 'components/button_toolbar'
      require_relative 'components/card'
      require_relative 'components/card_header'
      require_relative 'components/carousel'
      require_relative 'components/carousel_caption'
      require_relative 'components/carousel_control'
      require_relative 'components/carousel_indicators'
      require_relative 'components/carousel_item'
      require_relative 'components/collapse'
      require_relative 'components/dropdown'
      require_relative 'components/dropdown_divider'
      require_relative 'components/dropdown_header'
      require_relative 'components/dropdown_item'
      require_relative 'components/dropdown_menu'
      require_relative 'components/dropdown_toggle'
      require_relative 'components/embed'
      require_relative 'components/input_group'
      require_relative 'components/form'
      require_relative 'components/jumbotron'
      require_relative 'components/list_group'
      require_relative 'components/list_group_item'
      require_relative 'components/media'
      require_relative 'components/media_body'
      require_relative 'components/media_object'
      require_relative 'components/modal'
      require_relative 'components/modal_body'
      require_relative 'components/modal_footer'
      require_relative 'components/modal_header'
      require_relative 'components/nav'
      require_relative 'components/nav_item'
      require_relative 'components/nav_link'
      require_relative 'components/navbar'
      require_relative 'components/navbar_brand'
      require_relative 'components/navbar_nav'
      require_relative 'components/navbar_text'
      require_relative 'components/navbar_toggler'
      require_relative 'components/page_item'
      require_relative 'components/pagination'
      require_relative 'components/popover'
      require_relative 'components/progress'
      require_relative 'components/tab_content'
      require_relative 'components/tab_pane'
      require_relative 'components/table'
    end
  end
end
