ruby_version: ruby-2.3.7
bundler_version: 1.16.3
environment:
  RAILS_LOG_LEVEL: '2'
coverage: true
timeout: 300
test_pattern:
  - spec/**_spec.rb
test_exclude_pattern:
  - none
skip_package:
  - ruby
notify:
- channel: slack
  trigger-on: status-changed
  room: build_notifications
  team: networkforgood
  message: |
    -> %repo%/%branch% finished in %duration%s
    Committer: %committer%
    Failures: %failed-count%
    Passed: %passed-count%
    Commit: %commit%
    Build: %build-url%
