ruby_version: ruby-2.3.7
bundler_version: 1.16.3
environment:
  RAILS_LOG_LEVEL: '2'
coverage: true
timeout: 300
test_pattern:
  - spec/**_spec.rb
test_exclude_pattern:
  - none
skip_package:
  - ruby
hooks:
  pre_setup: gem install capybara-screenshot && gem install bundler -v 1.13.6 && bundle install --path=$HOME/bundle --no-deployment
  worker_setup: cd spec/test_app && bundle exec rake db:create db:schema:load
rerun_list:
  - spec/features/mapping_spec.rb
notify:
- channel: slack
  trigger-on: status-changed
  room: build_notifications
  team: networkforgood
  message: |
    -> %repo%/%branch% finished in %duration%s
    Committer: %committer%
    Failures: %failed-count%
    Passed: %passed-count%
    Commit: %commit%
    Build: %build-url%
