# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby'3.3.7'

gem 'execjs', '~> 2.7.0' # later versions break our deploy & publish processes; see DM and FP Gemfiles
gem 'haml', '~> 5.1'
gem 'nfg_ui', path: '..'
gem 'rails', '~> 6.0'
gem 'sass-rails', '~> 6.0'

group :development do
  gem 'byebug'
end

group :test do
  gem 'rspec'
end
