# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

gem 'execjs', '~> 2.7.0' # later versions break our deploy & publish processes; see DM and FP Gemfiles
gem 'haml', '~> 5.1'
gem 'nfg_ui', '~> 0.14', path: '..'
gem 'rails', '~> 5.2.4', '>= 5.2.4.5'
gem 'sass-rails', '~> 5.0'

group :development do
  gem 'byebug'
end

group :test do
  gem 'rspec'
end
