# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'nfg_ui_publisher/overwrite_guard'
require 'nfg_ui_publisher/uploader'

Rails.application.load_tasks

desc 'Compile nfg_ui assets and upload to S3 for public access. This command takes two arguments: the version number and an optional override flag'
task :publish, %i[nfg_ui_version override_flag] => %i[assets:clobber assets:precompile] do |_, nfg_ui_version: nil, override_flag: nil|
  find_aws = `which aws`

  if find_aws == ''
    abort 'ERROR: cannot find AWS CLI in $PATH. Please visit https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html for installation instructions'
  end

  if nfg_ui_version.blank?
    abort 'ERROR: must specify gem version to publish, for example: rake publish[0.11.0]'
  end

  uploader = NfgUiPublisher::Uploader.new(override_flag: override_flag)
  src_dir = "#{__dir__}/public/assets/"
  destination_uri = "s3://nfg-ui/v#{nfg_ui_version}"

  uploader.call(src_dir, destination_uri) do |err_msg|
    abort "Unable to upload assets due to error: #{err_msg}"
  end
end
